name: Synapse Environment Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: "dev"
        description: "Specifies the environment of the deployment."
      subscription_id:
        required: true
        type: string
        description: "Specifies the Azure subscription id."
      target_synapse_workspace_name:
        required: true
        type: string
        description: "Specifies the name of the target synapse workspace."
      target_synapse_workspace_resource_group_name:
        required: true
        type: string
        description: "Specifies the resource group name of the target synapse workspace."
      deployment:
        required: true
        type: boolean
        default: false
        description: "Specifies whether the deployment job should be executed."
    secrets:
      TENANT_ID:
        required: true
        description: "Specifies the tenant id of the deployment."
      CLIENT_ID:
        required: true
        description: "Specifies the client id."
      CLIENT_SECRET:
        required: true
        description: "Specifies the client secret."

env:
  SOURCE_SYNAPSE_WORKSPACE_NAME: ""
  SYNAPSE_ARTIFACTS_PATH: "code/synapse"
  SYNAPSE_DEPLOYMENT_SCRIPT_PATH: "code/scripts"

jobs:
  validation:
    name: Synapse Validation
    runs-on: [self-hosted]
    continue-on-error: false
    needs: []

    steps:
      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v4

      # Validate Synapse Artifacts
      - name: Validate Synapse Artifacts
        id: validation_synapse
        uses: azure/synapse-workspace-deployment@V1.8.0
        with:
          TargetWorkspaceName: ${{ inputs.target_synapse_workspace_name }}
          ArtifactsFolder: ${{ env.SYNAPSE_ARTIFACTS_PATH }}
          operation: "validate"
          deployManagedPrivateEndpoint: false
          DeleteArtifactsNotInTemplate: false

  deploy:
    name: Synapse Deployment
    runs-on: [self-hosted]
    continue-on-error: false
    environment: ${{ inputs.environment }}
    needs: [validation]

    steps:
      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v4

      # Login to Azure
      - name: Azure Login
        id: azure_login
        uses: azure/login@v1
        with:
          creds:  '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ inputs.subscription_id }}","tenantId":"${{ secrets.TENANT_ID }}"}'
          enable-AzPSSession: true

      # Install Required Modules
      - name: Install Required Modules
        id: install_modules
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Az -ErrorAction Stop
        shell: pwsh
        working-directory: "synapse/${{ env.SYNAPSE_DEPLOYMENT_SCRIPT_PATH }}"

      # Synapse Pre-Processing Step
      - name: Synapse Pre-Processing Step
        id: synapse_preprocessing
        run: |
          ./SynapseRolloutPreprocessing.ps1 `
            -SubscriptionId "${{ inputs.subscription_id }}" `
            -SynapseWorkspaceName "${{ inputs.target_synapse_workspace_name }}" `
            -CheckPastDaysOfPipelineRuns 1
        shell: pwsh
        working-directory: "synapse/${{ env.SYNAPSE_DEPLOYMENT_SCRIPT_PATH }}"

      # Deploy Synapse Artifacts
      - name: Deploy Synapse Artifacts
        id: deployment_synapse
        uses: azure/synapse-workspace-deployment@V1.8.0
        with:
          TargetWorkspaceName: ${{ inputs.target_synapse_workspace_name }}
          resourceGroup: ${{ inputs.target_synapse_workspace_resource_group_name }}
          TemplateFile: "synapse/${{ env.SOURCE_SYNAPSE_WORKSPACE_NAME }}/TemplateForWorkspace.json"
          ParametersFile: "rollout/tests/e2e/synapseConfig/params.synapse.json"
          # ArtifactsFolder:
          operation: "deploy"
          deployManagedPrivateEndpoint: false
          # OverrideArmParameters:
          DeleteArtifactsNotInTemplate: false
          Environment: "Azure Public"
          tenantId: ${{ secrets.TENANT_ID }}
          subscriptionId: ${{ inputs.subscription_id }}
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          managedIdentity: false

      # # Synapse Post-Processing Step
      # - name: Synapse Post-Processing Step
      #   id: synapse_postprocessing
      #   run: |
      #     ./SynapseRolloutPostprocessing.ps1 `
      #       -SubscriptionId "${{ inputs.subscription_id }}" `
      #       -SynapseWorkspaceName "${{ inputs.target_synapse_workspace_name }}" `
      #       -TriggerNames "${{ steps.synapse_preprocessing.outputs.triggerNames }}"
      #   shell: pwsh
      #   working-directory: "synapse/${{ env.SYNAPSE_DEPLOYMENT_SCRIPT_PATH }}"

      # Log out from Azure
      - name: Log out from Azure
        id: azure_logout
        run: |
          az logout
