name: Terraform Destroy Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: "dev"
        description: "Specifies the environment of the deployment."
      working_directory:
        required: true
        type: string
        description: "Specifies the working directory."
    secrets:
      CLIENT_ID:
        required: true
        description: "Specifies the client id."
      CLIENT_SECRET:
        required: true
        description: "Specifies the client secret."

jobs:
  deployment:
    name: Terraform Destroy
    runs-on: [self-hosted]
    continue-on-error: false
    environment: ${{ inputs.environment }}

    env:
      ARM_TENANT_ID: ${{ vars.TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_USE_OIDC: false

    steps:
      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v4

      # Terraform Init
      - name: Terraform Init
        working-directory: ${{ inputs.working_directory }}
        run: |
          terraform init

      # Terraform Destroy
      - name: Terraform Destroy
        working-directory: ${{ inputs.working_directory }}
        run: |
          terraform apply -var-file vars.${{ inputs.environment }}.tfvars  -auto-approve -input=false -destroy
