name: Azure ML Deployment Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Specifies the environment of the deployment."
      machine_learning_online_endpoint_name:
        required: true
        type: string
        description: "Specifies the name of the endpoint."
    secrets:
      CLIENT_ID:
        required: true
        description: "Specifies the client id."
      CLIENT_SECRET:
        required: true
        description: "Specifies the client secret."

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Model
    runs-on: [self-hosted]
    continue-on-error: false
    environment: ${{ inputs.environment }}

    steps:
      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v4

      # Login to Azure
      - name: Azure Login
        id: azure_login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ vars.SUBSCRIPTION_ID }}","tenantId":"${{ vars.TENANT_ID }}"}'

      # Install ML extension
      - name: Install ML Extension
        id: aml_install
        run: |
          az extension add -n ml

      # Create Online Deployment
      - name: Create Online Deployment
        id: aml_online_deployment
        run: |
          DEPLOYMENT_NAME=dep-${BASE_NAME:0:28}
          az ml online-deployment create \
            --resource-group ${{ vars.RESOURCE_GROUP_NAME }} \
            --workspace-name ${{ vars.ML_WORKSPACE_NAME }} \
            --endpoint-name ${{ inputs.machine_learning_online_endpoint_name }} \
            --name $DEPLOYMENT_NAME \
            --file ${{ github.workspace }}/code/ml/score-online/deployment.yml \
            --all-traffic
        env:
          BASE_NAME: "${{ github.run_attempt }}-${{ github.sha }}"

      # Invoke Online Deployment
      - name: Invoke Online Deployment
        id: aml_online_endpoint_invoke
        run: |
          az ml online-endpoint invoke \
            --resource-group ${{ vars.RESOURCE_GROUP_NAME }} \
            --workspace-name ${{ vars.ML_WORKSPACE_NAME }} \
            --name ${{ inputs.machine_learning_online_endpoint_name }} \
            --request-file ${{ github.workspace }}/code/ml/score-online/sample-request.json

      # Log out from Azure
      - name: Log out from Azure
        id: azure_logout
        run: |
          az logout
