name: Azure ML Training Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: "dev"
        description: "Specifies the environment of the deployment."
    secrets:
      CLIENT_ID:
        required: true
        description: "Specifies the client id."
      CLIENT_SECRET:
        required: true
        description: "Specifies the client secret."
    outputs:
      machine_learning_job_name:
        description: "The name of the machine learning job."
        value: ${{ jobs.train.outputs.machine_learning_job_name }}

permissions:
  id-token: write
  contents: read

jobs:
  train:
    name: Train model
    runs-on: [self-hosted]
    continue-on-error: false
    environment: ${{ inputs.environment }}
    outputs:
      machine_learning_job_name: ${{ steps.aml_job.outputs.machine_learning_job_name }}

    steps:
      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v4

      # Login to Azure
      - name: Azure Login
        id: azure_login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ vars.SUBSCRIPTION_ID }}","tenantId":"${{ vars.TENANT_ID }}"}'

      # Install ML extension
      - name: Install ML Extension
        id: aml_install
        run: |
          az extension add -n ml

      # Create Dataset
      - name: Create Dataset
        id: aml_dataset
        run: |
          az ml data create \
            --resource-group ${{ vars.AZURE_RESOURCE_GROUP_NAME }} \
            --workspace-name ${{ vars.AZURE_ML_WORKSPACE_NAME }} \
            --file ${{ github.workspace }}/code/ml/data/diabetes_mltable.yml

      # Create Job
      - name: Create Job
        id: aml_job
        run: |
          az ml job create \
            --resource-group ${{ vars.AZURE_RESOURCE_GROUP_NAME }} \
            --workspace-name ${{ vars.AZURE_ML_WORKSPACE_NAME }} \
            --name $JOB_NAME \
            --file ${{ github.workspace }}/code/ml/train/pipeline.yml \
            --stream

          STUDIO_URL=$(az ml job show --name $JOB_NAME --resource-group ${{ vars.AZURE_RESOURCE_GROUP_NAME }} --workspace-name ${{ vars.AZURE_ML_WORKSPACE_NAME }} --query services.Studio.endpoint | jq -r)

          echo "studio_url=$STUDIO_URL" >> $GITHUB_OUTPUT
          echo "machine_learning_job_name=$JOB_NAME" >> $GITHUB_OUTPUT
        env:
          JOB_NAME: "Job-${{ github.sha }}"

      # Log out from Azure
      - name: Log out from Azure
        id: azure_logout
        run: |
          az logout
