name: Terraform Deployment
on:
  push:
    branches:
      - main
    paths:
      - "**.tf"
      - "**.yml"
      - "**.yaml"
      - "!.github/workflows/**"
      - "!.pre-commit-config.yaml"
      - "!.terraform-docs.yml"

  pull_request:
    branches:
      - main
    paths:
      - "**.tf"
      - "**.yml"
      - "**.yaml"
      - "!.github/workflows/**"
      - "!.pre-commit-config.yaml"
      - "!.terraform-docs.yml"

jobs:
  terraform:
    uses: ./.github/workflows/_terraformEnvironmentTemplate.yml
    name: "Terraform Deployment"
    with:
      environment: "dev"
      working_directory: "./tests/e2e"
      subscription_id: "8f171ff9-2b5b-4f0f-aed5-7fa360a1d094"
    secrets:
      TENANT_ID: ${{ secrets.TENANT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
